# Generated by Django 6.0.4 on 2026-06-25 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Food', 'Food'), ('Groceries', 'Groceries'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Salary', max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='types',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
