# Generated by Django 6.0.4 on 2026-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_transactions_category_transactions_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
