# Generated by Django 6.0.4 on 2026-06-26 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
