# Generated by Django 6.0.4 on 2026-07-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='limit',
        ),
    ]
